# Generated by Django 2.2.16 on 2020-09-10 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_auto_20200910_1226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='cliente',
            new_name='user',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
