# Generated by Django 2.2.16 on 2020-09-10 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_auto_20200910_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created_date',
        ),
    ]
