# Generated by Django 2.2.16 on 2020-09-10 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_remove_product_created_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='title',
            new_name='name',
        ),
    ]
